[project]
name = "build-a-rig"
version = "0.1.0"
description = "An AI-guided PC configurator."

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"] 