[project]
name = "ai_project"
version = "0.1.0"
description = "A PC builder assistant powered by AI."

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"] 